POST http://localhost:3333/events
Content-Type: application/json

{
  "title": "Evento Dev",
  "details": "Conferencia de desenvolvimento de software com palestras sobre IA",
  "maximumAttendees": 260
}

###

POST http://localhost:3333/events/877904e7-08d5-4881-a900-cad588805843/attendees
Content-Type: application/json

{
  "name": "Diego",
  "email": "diego@rdevsoftware.com.br"
}

###

GET http://localhost:3333/events/877904e7-08d5-4881-a900-cad588805843

###

GET http://localhost:3333/attendees/5/badge
###

GET http://localhost:3333/attendees/5/check-in

###

GET http://localhost:3333/events/877904e7-08d5-4881-a900-cad588805843/attendees?query=diego